/*******************************************************************************
 * File Name: project.h
 * PSoC Creator  3.1 SP2
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2013, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/

#include <cyfitter_cfg.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <cydisabledsheets.h>
#include <Bootloadable_1.h>
#include <UART_1.h>
#include <UART_1_SPI_UART.h>
#include <UART_1_PINS.h>
#include <UART_1_SPI_UART_PVT.h>
#include <UART_1_PVT.h>
#include <UART_1_BOOT.h>
#include <PWM_1.h>
#include <Clock_1.h>
#include <Pin_1_2.h>
#include <Pin_1_2_aliases.h>
#include <Pin_1_0.h>
#include <Pin_1_0_aliases.h>
#include <Pin_1_1.h>
#include <Pin_1_1_aliases.h>
#include <Pin_1_6.h>
#include <Pin_1_6_aliases.h>
#include <pin_button.h>
#include <pin_button_aliases.h>
#include <Timer_CH1.h>
#include <Timer_CH2.h>
#include <Pin_2_7.h>
#include <Pin_2_7_aliases.h>
#include <Pin_3_0.h>
#include <Pin_3_0_aliases.h>
#include <isr_CH1.h>
#include <isr_CH2.h>
#include <PWM_2.h>
#include <Pin_0_4.h>
#include <Pin_0_4_aliases.h>
#include <Pin_0_6.h>
#include <Pin_0_6_aliases.h>
#include <Pin_0_5.h>
#include <Pin_0_5_aliases.h>
#include <UART_1_SCBCLK.h>
#include <UART_1_tx.h>
#include <UART_1_tx_aliases.h>
#include <UART_1_rx.h>
#include <UART_1_rx_aliases.h>
#include <core_cm0_psoc4.h>
#include <core_cm0.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cyPm.h>
#include <cytypes.h>
#include <cypins.h>
#include <core_cmFunc.h>
#include <core_cmInstr.h>

/*[]*/

